export const START_PROCESSING='START_PROCESSING';
export const END_PROCESSING='END_PROCESSING';

export const APP_GET_INIT_DATA='APP/GET_INIT_DATA';
export const APP_AUTH='APP/AUTH';
export const APP_SET_USER_NAME='APP/SET_USER_NAME';
export const APP_REDIRECT='APP/REDIRECT';
export const APP_CLEAR_USER_NAME='APP/CLEAR_USER_NAME';

export const APP_ENTER_CHAT='APP/ENTER_CHAT';
export const APP_INIT_ROOM='APP/INIT_ROOM';

export const CHAT_SHOW_ALERT='CHAT/SHOW_ALERT';
export const CHAT_HIDE_ALERT='CHAT/HIDE_ALERT';
export const CHAT_GET_ROOMS='CHAT/GET_ROOMS';
export const CHAT_SEND_MESSAGE='CHAT/SEND_MESSAGE';
export const CHAT_INIT_ROOM='CHAT/INIT_ROOM';
export const CHAT_UPDATE_ROOMS='CHAT/UPDATE_ROOMS';
export const CHAT_UPDATE_USERS='CHAT/UPDATE_USERS';
export const CHAT_ADD_NEW_MESSAGE='CHAT/ADD_NEW_MESSAGE';
export const CHAT_CREATE_NEW_ROOM='CHAT/CREATE_NEW_ROOM';

